### ISSUE TITLE
fail url

### ISSUE THREAD

**Issue by LedzCop** [velali/WO_BOG_PAYMENT#1]
ლევან გამარჯობა, პირველ რიგში მადლობა პლაგინის დაწერისთვის, ჩემი აზრით ეს აკლია  class ფაილში, ნუ ზოგადად რაც გადავხედე რა

`'api_backurl_f' => array(
                'title'     => __( 'Back url "fail"', '' ),
                'type'      => 'text',
                'desc_tip'  => __( 'Back url გადახდის წარუმატებლობის განხორციელების შემთხვევაში', '' ),
            ),`

**Comment by velali** [comment]
მოგვარებულია და მართვადია სამართავი პანელიდან.
